name: 🔍 SAST - Semgrep

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main, master]

jobs:
  semgrep:
    name: Analyse statique du code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/owasp-top-ten
            p/javascript
            p/secrets
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
